export default [
    {title: "New report card shows a stressed CPS in key academics, absenteeism",
    url:"https://www.columbiamissourian.com/news/k12_education/new-report-card-shows-a-stressed-cps-in-key-academics-absenteeism/article_aaeda1fc-bcd6-11ed-8ebf-c7f887e44183.html"},
    {title:"UM System generated $6.5 billion in economic impact in 2020-21", 
    url:"https://www.columbiamissourian.com/special_section/spotlight/um-system-generated-6-5-billion-in-economic-impact-in-2020-21/article_46df1ff4-7a75-11ed-84fc-e36d58c6beda.html"},
    {title: "With new challenges, reliance on hospital and universities will be important", 
    url:"https://www.columbiamissourian.com/special_section/spotlight/with-new-challenges-reliance-on-hospital-and-universities-will-be-important/article_1c2ebde8-7a46-11ed-b117-47619f96f851.html"},
    {title: "A breakdown of the mixed economy in a Midwest college town", 
    url: "https://www.columbiamissourian.com/special_section/spotlight/a-breakdown-of-the-mixed-economy-in-a-midwest-college-town/article_7af71720-7bc8-11ed-9739-3b3fecf0543b.html"},
    {title: "Evaluation technique meant to help administrators give teachers better feedback",
    url:"https://www.columbiamissourian.com/news/k12_education/evaluation-technique-meant-to-help-administrators-give-teachers-better-feedback/article_0f53a9a8-7654-11ed-8a05-e7f8ed1aced0.html"},
    {title: "With COVID closures in the rear-view mirror, CPS focuses on the next five years", 
    url: "https://www.columbiamissourian.com/news/k12_education/with-covid-closures-in-the-rear-view-mirror-cps-focuses-on-the-next-five-years/article_ba185b50-554c-11ed-820e-4f949545fb8e.html"},
    {title:"KBIA celebrates 50 years, raises more than $90,000 and shatters one-day fundraising record", 
    url: "https://www.columbiamissourian.com/news/higher_education/kbia-celebrates-50-years-raises-more-than-90-000-and-shatters-one-day-fundraising-record/article_cbd4a5da-cfd0-11ec-b7c8-0fab59da85c6.html"},
    {title: "Retiring Fairview principal made place-based learning a schoolwide mission", 
    url: "https://www.columbiamissourian.com/news/k12_education/retiring-fairview-principal-made-place-based-learning-a-schoolwide-mission/article_42632faa-c829-11ec-a175-0f9312b8d575.html"},
    {title: "Seven sites across Boone County to hold prescription drug takeback", 
    url: "https://www.columbiamissourian.com/news/local/seven-sites-across-boone-county-to-hold-prescription-drug-takeback/article_9bfde134-c4b6-11ec-a6b6-33edc6f56c43.html"},
    {title: "Caring for Columbia organizes over 300 MU student volunteers",
    url: "https://www.columbiamissourian.com/news/local/caring-for-columbia-organizes-over-300-mu-student-volunteers/article_e50ab0ce-b826-11ec-a659-e79228ed6bc1.html"},
    {title: "CPS board hears about student success, staff recruitment and retention", 
    url: "https://www.columbiamissourian.com/news/k12_education/cps-board-hears-about-student-success-staff-recruitment-and-retention/article_3e0ff2f0-aae5-11ec-b080-d73bcd65bfac.html"},
    {title: "Columbia police arrest suspect for Sunday homicide",
    url: "https://www.columbiamissourian.com/news/local/columbia-police-arrest-suspect-for-sunday-homicide/article_424d3afa-a92b-11ec-9015-e36fa8e1561f.html"},
    {title: "True/False Film Fest sees increase in ticket sales, still half of pre-pandemic levels",
    url: "https://www.columbiamissourian.com/news/local/true-false-film-fest-sees-increase-in-ticket-sales-still-half-of-pre-pandemic-levels/article_4198481a-9e55-11ec-8e23-cf949116715b.html"},
    {title: "Suspect arrested in Saturday shooting that injured one",
    url: "https://www.columbiamissourian.com/news/local/suspect-arrested-in-saturday-shooting-that-injured-one/article_5ce41838-9e3c-11ec-b999-a3ec91479785.html"},
    {title: "United Community Builders to open new community center in northeastern Columbia",
    url: "https://www.columbiamissourian.com/news/local/united-community-builders-to-open-new-community-center-in-northeastern-columbia/article_5d822aac-9674-11ec-a4ea-9feb89fc41e8.html"},
    {title: "Randy Harper told stories with a smile",
    url: "https://www.columbiamissourian.com/obituaries/randy-harper-told-stories-with-a-smile/article_5e29d494-9405-11ec-bcfe-2b09843f9ab7.html"},
    {title:"Boone Hospital increases visitor policy to two per day",
    url: "https://www.columbiamissourian.com/news/local/boone-hospital-increases-visitor-policy-to-two-per-day/article_e41fed56-9336-11ec-9b90-9f6bc91c6429.html"},
    {title: "Hickman High principal announces he is leaving; new Lange Middle principal named",
    url: "https://www.columbiamissourian.com/news/k12_education/hickman-high-principal-announces-he-is-leaving-new-lange-middle-principal-named/article_1de05452-8b6e-11ec-9e6e-5bc65c9ab1da.html"},
    {title: "New Schnucks to open by April; Moser's to move in May",
    url: "https://www.columbiamissourian.com/news/local/new-schnucks-to-open-by-april-mosers-to-move-in-may/article_abe2fb78-8854-11ec-9e2c-ef69aa6b75f6.html"},
    {title:"Jennings Premium Meats to close retail location, focus on wholesale",
    url: "https://www.columbiamissourian.com/news/local/jennings-premium-meats-to-close-retail-location-focus-on-wholesale/article_b7413388-7d5d-11ec-867c-c7ca3c74e9d5.html"},
    {title: "Wabash to open as overnight shelter Monday, Tuesday and Thursday",
    url: "https://www.columbiamissourian.com/news/local/wabash-to-open-as-overnight-shelter-monday-tuesday-and-thursday/article_d93a55fc-7d38-11ec-a037-7b39e5c366a4.html"},
    {title: "Wabash Station is shelter of last resort for homeless",
    url: "https://www.columbiamissourian.com/news/local/wabash-station-is-shelter-of-last-resort-for-homeless/article_e7799fbc-5ec3-11ec-b72d-0b98c77777bc.html"}

]